version: '3'

services:
  app:
    image: thecodingmachine/php:${PHP_VERSION:-7.4}-v4-cli
    environment:
      TYPO3_VERSION: ${TYPO3_VERSION:-^9.5}
      TYPO3_API_PASSWORD:
      TYPO3_API_USERNAME:
    volumes:
      - ./:/usr/src/app
